### PR TITLE
NOJIRA Updating from Font Awesome v4.0.3 to v4.7.0

### PR DESCRIPTION
**Pull request by jonathanmtran**

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
Build failure is unrelated to this commit, Travis CI used the fallback Ruby build configuration instead of a Java config.
I'll put together a PR to resolve this shortly.

**Comment by ChristianMurphy** [comment]
https://github.com/Jasig/NotificationPortlet/pull/44 Corrects Travis CI configuration

**Comment by ChristianMurphy** [comment]
@jonathanmtran a merge conflict cropped up for this PR, could you get that resolved?

**Comment by jonathanmtran** [comment]
@ChristianMurphy All done

**Pull request merged**
