### PR TITLE
NOTIFPLT-89: Set hibernate.dialect at runtime in Spring rather than b…

### PR DESCRIPTION
**Pull request by bjagg**
…uild time.

https://issues.jasig.org/browse/NOTIFPLT-89

### CODE REVIEW

**Comment by drewwills** [comment]
You are made of awesome @bjagg !

**Comment by drewwills** [comment]
Is this one really still `[WIP]`?

**Comment by drewwills** [comment]
I tested this one locally (on MS SQL Server) and it appears to work correctly.

@bjagg can you confirm/deny whether you intend to do anything else to it?

**Comment by bjagg** [comment]
Yep, works for me with MS SQL Server

**Pull request merged**
