### PR TITLE
fix: ie support

### PR DESCRIPTION
**Pull request by ChristianMurphy**
simplified code and removes an unneeded ref.

Adds custom components for ie and edge with fewer features to avoid infinite recursion.

### CODE REVIEW

**Comment by drewwills** [comment]
Taking a look now.

**Comment by ChristianMurphy** [comment]
It's less broken, there's still an issue with the slot.

**Comment by drewwills** [comment]
Can you talk in 30 min or so?  (I'd like to explore whether we can avoid the use of slots, for now.)

**Comment by ChristianMurphy** [comment]
@drewwills sure

**Comment by ChristianMurphy** [comment]
@drewwills this PR now includes the follow up fixes for Edge and IE

**Comment by drewwills** [comment]
Excellent, I'll pull it down tomorrow.

**Comment by drewwills** [comment]
This IE fix looks "good" to me.

I like how they are organized into other file(s), how they are very slim, and how they are thoroughly-commented.

**Comment by drewwills** [comment]
This solution appears to be working now -- ready for merge, AFAIK.

**Pull request merged**
